version: "3.9"
services:
  documents:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "documents"
      POSTGRES_USER: "documents"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
