version: "3.9"
services:
  documents:
    image: cr.yandex/crp7mjicr08l7dq8o6ek/documents:latest
    network_mode: host
    environment:
      - DBPASSWORD
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - CONFIG=/app/configs/prod.yaml
    volumes:
      - ./configs:/app/configs
    healthcheck:
      test: curl --fail http://localhost:8080/api/ping || exit 1
      interval: 15s
      retries: 3
      start_period: 5s
      timeout: 10s
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://${LOKI_USERNAME}:${LOKI_PASSWORD}@logs-prod-eu-west-0.grafana.net/api/prom/push"
  documents-frontend:
    image: cr.yandex/crp7mjicr08l7dq8o6ek/documents-frontend:latest
    depends_on:
      - documents
    network_mode: host
    restart: unless-stopped
    logging:
      driver: local
  nginx:
    image: nginx
    network_mode: host
    depends_on:
      - documents-frontend
      - documents
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:80/ping || exit 1
      interval: 15s
      retries: 3
      start_period: 5s
      timeout: 10s
    logging:
      driver: local
  grafana-agent:
    image: grafana/agent:latest
    network_mode: host
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent/config.river
    environment:
      - AGENT_MODE=flow
      - GRAFANA_AGENT_USERNAME
      - GRAFANA_AGENT_PASSWORD
    volumes:
      - ./configs/config.river:/etc/agent/config.river
    logging:
      driver: local
