version: "3.9"
services:
  documents:
    image: cr.yandex/crp7mjicr08l7dq8o6ek/documents:latest
    network_mode: "host"
    environment:
      - DBPASSWORD
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - CONFIG=/app/configs/prod.yaml
    volumes:
      - ./configs:/app/configs
    healthcheck:
      test: curl --fail http://localhost:8080/api/ping || exit 1
      interval: 15s
      retries: 3
      start_period: 5s
      timeout: 10s
    restart: always
  documents-frontend:
    image: cr.yandex/crp7mjicr08l7dq8o6ek/documents-frontend:latest
    depends_on:
      - documents
    network_mode: "host"
    restart: always
  nginx:
    image: nginx
    network_mode: "host"
    depends_on:
      - documents-frontend
      - documents
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/.well-known:/www/.well-known
    restart: always
    healthcheck:
      test: curl --fail http://localhost:80/ping || exit 1
      interval: 15s
      retries: 3
      start_period: 5s
      timeout: 10s
