server:
  host: localhost
  port: 8080
  cors_origin: http://localhost:3000
  callbacks:
    back_redirect_url: http://localhost:3000/
    google:
      redirect_url: http://localhost:8080/api/auth/google/callback

storage:
  hosts:
    - host.docker.internal:5432
    - localhost:5432
  username: documents
  password_env: DBPASSWORD
  db_name: documents
