logging:
  stdout_path: "example.log"
  stderr_path: "example_err.log"

server:
  port: 8080

storage:
  hosts:
    - rc1a-fbd6flp6bw3aakyu.mdb.yandexcloud.net:27018
  username: superuser
  password_env: DBPASSWORD
  db_name: documents
  cert_file_path: "/Users/kraysent/.mongodb/root.crt"