logging:
  stdout_path: "example.log"
  stderr_path: "example_err.log"

server:
  port: 8080

storage:
  host: localhost
  port: 5432
  username: documents
  password_env: DBPASSWORD
  db_name: documents
