server:
  host: localhost
  port: 8080
  callbacks:
    google:
      redirect_url: http://localhost/api/auth/google/callback

storage:
  hosts:
    - host.docker.internal:5432
    - localhost:5432
  username: documents
  password_env: DBPASSWORD
  db_name: documents
