server:
  host: docarchive.space
  port: 8080
  callbacks:
    back_redirect_url: https://docarchive.space/
    google:
      redirect_url: https://docarchive.space/api/auth/google/callback

storage:
  hosts:
    - c-c9qurglps80g3pihm245.rw.mdb.yandexcloud.net:6432
  username: documents
  password_env: DBPASSWORD
  db_name: documentsdb
  ssl_mode: require
  ssl_root_cert_path: /.ssl/root.crt
